/* Load this script using conditional IE comments if you need to support IE 7 and IE 6. */

window.onload = function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'JoomBlogSet\'">' + entity + '</span>' + html;
	}
	var icons = {
			'jb-icon-bold' : '&#xe057;',
			'jb-icon-italic' : '&#xe003;',
			'jb-icon-underline' : '&#xe005;',
			'jb-icon-link' : '&#xe015;',
			'jb-icon-list-bullet' : '&#xe016;',
			'jb-icon-list-numbered' : '&#xe017;',
			'jb-icon-calendar' : '&#xe018;',
			'jb-icon-image' : '&#xe019;',
			'jb-icon-eye' : '&#xe01a;',
			'jb-icon-cross' : '&#xe01b;',
			'jb-icon-tip' : '&#xe01c;',
			'jb-icon-alert' : '&#xe01d;',
			'jb-icon-home' : '&#xe020;',
			'jb-icon-blog' : '&#xe022;',
			'jb-icon-pencil' : '&#xf0d7;',
			'jb-icon-quill' : '&#xf014;',
			'jb-icon-pen' : '&#xe007;',
			'jb-icon-posts' : '&#xe025;',
			'jb-icon-comments' : '&#xf015;',
			'jb-icon-comment' : '&#xf0dd;',
			'jb-icon-stats-pie' : '&#xf0de;',
			'jb-icon-stats-graph' : '&#xf09c;',
			'jb-icon-stats-bars' : '&#xf074;',
			'jb-icon-stats-chart' : '&#xe026;',
			'jb-icon-settings' : '&#xe002;',
			'jb-icon-cog-6' : '&#xe027;',
			'jb-icon-cog-8' : '&#xe028;',
			'jb-icon-cogs' : '&#xe00d;',
			'jb-icon-checkbox-checked' : '&#xe024;',
			'jb-icon-checkbox-unchecked' : '&#xe02a;',
			'jb-icon-checkbox-partial' : '&#xf0e2;',
			'jb-icon-radio-checked' : '&#xf0d8;',
			'jb-icon-radio-unchecked' : '&#xf0d9;',
			'jb-icon-trash' : '&#xf0da;',
			'jb-icon-search' : '&#xf0dc;',
			'jb-icon-caret-down' : '&#xf104;',
			'jb-icon-caret-up' : '&#xf107;',
			'jb-icon-caret-left' : '&#xf106;',
			'jb-icon-caret-right' : '&#xf105;',
			'jb-icon-sort' : '&#xf002;',
			'jb-icon-sort-up' : '&#xe01e;',
			'jb-icon-sort-down' : '&#xe021;',
			'jb-icon-angle-down' : '&#xe02c;',
			'jb-icon-angle-up' : '&#xe02e;',
			'jb-icon-angle-left' : '&#xe02f;',
			'jb-icon-angle-right' : '&#xe030;',
			'jb-icon-arrow-left' : '&#xe031;',
			'jb-icon-arrow-right' : '&#xe032;',
			'jb-icon-star-empty' : '&#xe036;',
			'jb-icon-star-half' : '&#xe037;',
			'jb-icon-star' : '&#xe038;',
			'jb-icon-like' : '&#xf10d;',
			'jb-icon-dislike' : '&#xf10e;',
			'jb-icon-heart' : '&#xe03b;',
			'jb-icon-heart-broken' : '&#xe03c;',
			'jb-icon-quote-left' : '&#xe03e;',
			'jb-icon-quote-right' : '&#xe05c;',
			'jb-icon-checkmark-circle' : '&#xf005;',
			'jb-icon-cancel-circle' : '&#xf006;',
			'jb-icon-backspace' : '&#xf089;',
			'jb-icon-tag-left' : '&#xe03f;',
			'jb-icon-tags-left' : '&#xe040;',
			'jb-icon-tag-right' : '&#xe001;',
			'jb-icon-tags-right' : '&#xe004;',
			'jb-icon-categories' : '&#xe006;',
			'jb-icon-history' : '&#xe008;',
			'jb-icon-clock-light' : '&#xe009;',
			'jb-icon-clock-dark' : '&#xf02b;',
			'jb-icon-camera' : '&#xf02c;',
			'jb-icon-user' : '&#xf03e;',
			'jb-icon-group' : '&#xf0e8;',
			'jb-icon-profile' : '&#xf0eb;',
			'jb-icon-random' : '&#xe00a;',
			'jb-icon-video' : '&#xe00b;',
			'jb-icon-loop' : '&#xe00c;',
			'jb-icon-code' : '&#xe00e;',
			'jb-icon-hits' : '&#xe00f;',
			'jb-icon-lock' : '&#xe010;',
			'jb-icon-unlock' : '&#xe011;',
			'jb-icon-directions' : '&#xe012;',
			'jb-icon-rocket' : '&#xe013;',
			'jb-icon-flag' : '&#xe014;',
			'jb-icon-award' : '&#xe01f;',
			'jb-icon-busy' : '&#xe023;',
			'jb-icon-undo' : '&#xe029;',
			'jb-icon-tweet' : '&#xe02b;',
			'jb-icon-earth' : '&#xe02d;',
			'jb-icon-share' : '&#xe033;',
			'jb-icon-feed' : '&#xe034;',
			'jb-icon-mail' : '&#xe035;',
			'jb-icon-facebook' : '&#xe039;',
			'jb-icon-twitter' : '&#xe03a;',
			'jb-icon-linkedin' : '&#xe03d;',
			'jb-icon-google-plus' : '&#xe041;',
			'jb-icon-pinterest' : '&#xe05d;',
			'jb-icon-smiley-light' : '&#xe05e;',
			'jb-icon-smiley-dark' : '&#xe05f;',
			'jb-icon-happy-light' : '&#xe042;',
			'jb-icon-happy-dark' : '&#xe043;',
			'jb-icon-tongue-light' : '&#xe044;',
			'jb-icon-tongue-dark' : '&#xe045;',
			'jb-icon-sad-light' : '&#xe046;',
			'jb-icon-sad-dark' : '&#xe047;',
			'jb-icon-neutral-light' : '&#xe048;',
			'jb-icon-neutral-dark' : '&#xe049;',
			'jb-icon-confused-light' : '&#xe04a;',
			'jb-icon-confused-dark' : '&#xe04b;',
			'jb-icon-shocked-light' : '&#xe04c;',
			'jb-icon-shocked-dark' : '&#xe04d;',
			'jb-icon-wondering-light' : '&#xe04e;',
			'jb-icon-wondering-dark' : '&#xe04f;',
			'jb-icon-wink-light' : '&#xe050;',
			'jb-icon-wink-dark' : '&#xe051;',
			'jb-icon-cool-light' : '&#xe052;',
			'jb-icon-cool-dark' : '&#xe053;',
			'jb-icon-angry-light' : '&#xe054;',
			'jb-icon-angry-dark' : '&#xe055;',
			'jb-icon-grin-light' : '&#xe056;',
			'jb-icon-grin-dark' : '&#xe000;',
			'jb-icon-evil-light' : '&#xf073;',
			'jb-icon-evil-dark' : '&#xe058;',
			'jb-icon-google-plus-2' : '&#xe059;',
			'jb-icon-heart-2' : '&#xe05a;',
			'jb-icon-paper-clip' : '&#xf0c6;',
			'jb-icon-inbox' : '&#xe060;',
			'jb-icon-refresh' : '&#xe061;',
			'jb-icon-volume' : '&#xe062;',
			'jb-icon-info' : '&#xe05b;',
			'jb-icon-untitled' : '&#xe063;'
		},
		els = document.getElementsByTagName('*'),
		i, attr, html, c, el;
	for (i = 0; ; i += 1) {
		el = els[i];
		if(!el) {
			break;
		}
		attr = el.getAttribute('data-icon');
		if (attr) {
			addIcon(el, attr);
		}
		c = el.className;
		c = c.match(/jb-icon-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
};